name: Build and Publish Docker Image

on:
  push:
    branches:
    - development
    paths:
    - '.github/Dockerfile'
    - '.github/workflows/docker-build-publish.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .github/Dockerfile
        push: true
        tags: |
          ghcr.io/quiltai/gh-action:python-3.9-uv-ruff
          ghcr.io/quiltai/gh-action:latest
